version: '2'
services:
  # this is our kafka cluster.
  kafka-cluster:
    container_name: kafka
    image: landoop/fast-data-dev:cp3.3.0
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    env_file: .env

  postgres:
    container_name: postgres
    image: postgres:13.3
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./volumes/app/postgres:/var/lib/postgresql/data
    env_file: .env
